name: Scraping Nocturno

on:
  schedule:
    - cron: '0 2 * * *' # Se ejecuta a las 2:00 AM UTC todos los días
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para poder hacer commit de vuelta al repositorio

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # Acelera la instalación de dependencias

    - name: Instalar Ubuntu Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Instalar dependencias de Python
      run: |
        pip install -r requirements.txt

    - name: Ejecutar Scraping
      run: |
        python league_scraping.py
        
    - name: Ejecutar Análisis ELO
      run: |
        python simulacion_final.py

    - name: Hacer commit y push de los nuevos JSONs
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add jsons/*.json
        git add frontend/public/*.json
        git commit -m "Actualización nocturna de resultados y ELO" || echo "No hay cambios para commitear"
        git push
